Repository Uvesh99/stack_movies, pull requests merged in 2025-01, with the labels that each got.

#13 Improved and Updated Dashboard, Theater, and Movies Card UI
  frontend/src/api/Reservation_api/Reservation.js
  frontend/src/components/Admin/Admin.jsx
  frontend/src/components/Theater/Theater.jsx
  frontend/src/components/Theater/TheaterMovies.jsx
  frontend/src/components/User/User.jsx
Labels: Level 2

#18 feat : Added a SearchBar and searchFeature
  frontend/src/common/Header/Header.jsx
  frontend/src/components/homes/home.css
Labels: swoc, intermediate

#20 Added on key 'enter' feature and pop up
  frontend/src/common/Header/Header.jsx
Labels: beginner

#24 feat/ modify the search section
  frontend/src/common/Header/Header.jsx
Labels: swoc, beginner

#27 Movie UI change
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/common/Header/Header.css
  frontend/src/common/Header/Header.jsx
  frontend/src/components/Movies/MoviePage.css
  frontend/src/components/Movies/MoviePage.jsx
  frontend/src/components/homes/# Code Citations.md
  frontend/src/components/homes/HomeCard.jsx
  frontend/src/components/homes/home.css
  frontend/src/home/HomePage.jsx
Labels: enhancement, swoc, intermediate

#37 Update icon + meta data + title
  frontend/index.html
  frontend/public/Logo_.svg
  frontend/src/common/Footer/Footer.jsx
  frontend/src/common/Header/Header.jsx
Labels: swoc, beginner
